sudo: false

language: ruby

rvm:
  - 2.5.3

branches:
  only:
    - v1_cn
    - v1_en
    - dm_cn
    - dm_en
    - coin_margined_swap_cn
    - coin_margined_swap_en
    - usdt_swap_cn
    - usdt_swap_en
    - option_cn
    - option_en

cache: bundler

script:
  - ./deploy.sh


secure: "gXH63YqePtea6quwooHGScmGfVroK6ZuH3KcC4eJVvcIbySBoUfjXtwvhz82rhaQH3UyE4ei6jLB0orDhP75/Ko550SWhJ3CNF8N6pa/Kl8bqqC8AUdiDRhlYpa6wW1amnY2W9K2T/kdIW7xW4VaNYuylkaq/XPEvT5HpkwPaVENy9IMxCiSaGIzyb8KtDrJ8e00SgaFXlUjx2GFzR9Yy2KQRNYE1heFGQOmKY9LhOPZafwNyw9FGPG8891qyWOx/q9x/R76NmIgGu8MHQ5ZOOSnoAU2cKXdJ713VYp5YakUwQE8bdUm7E+rLViA6KuYSaqdy12tUmen+IrcyA3cu+RcvKUlMsGtaHHYB/na1pdBOf+5m1lB7z2vIOuF1Xzj7d1Ii9AIsZX32PXuD36+Q0/KvKrCxTlvnVH72KoczJqr5N/yVfgj5V4on/zxV6Ws3SZB2VFtqsJMwKPLnpKnibvKI/1ttr/2+gnwLXpeRWtPCD7qGPG86hcK23Z1HmFBp8a8AGZThPoW1C/N/jlemJQ+XMQnf+gUMSrWi/q1La/AZyxWdaoVDlzmda4++CH95GhsM7BgiiXtt4AJPQeYWYHySHvrU7fkK7Ah6uiWUYzauk9SVFU9U8qKOrWrQ2W3CIBNCU0FMyN5qcoylNJjQbHz36twGbWwIc7dkyqBP98="
